OOP school library: set up associations
LokurasRlz/OOP-School-Library pull request #3
Opened 2022-11-04 21:29 UTC by LokurasRlz

# In this branch, I have worked on the following things: 

- Established has-many relationships between Classroom and Student Classes ✔️ 
- Established many-many relationships between Persons and Book Classes using the intermediary Rental class. ✔️

2022-11-04 21:51 UTC, mmsesay requested changes
Hi @LokurasRlz,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
 - Good Readme :heavy_check_mark: 
 - No linter error :heavy_check_mark: 
 - Good PR title :heavy_check_mark: 
 - Good PR summary :heavy_check_mark:  


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 21:51 UTC, mmsesay commented on rental.rb
> +  attr_accessor :date
- [ ] Getters and Setters for @book and @person instance variables should be present.

2022-11-04 21:51 UTC, mmsesay commented on person.rb
> +  attr_reader :id, :rentals
- [ ] Getters and Setters for @rentals should be present. Please remove `:rentals` from `attr_reader` and set it to `attr_accessor`

2022-11-05 02:48 UTC, danielufeli approved these changes
Hi @mmsesay ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![ChopApproveCopApproveGIF](https://user-images.githubusercontent.com/48371156/200094064-25efa74f-2f0c-4f2f-9129-28b06b04359b.gif)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Code✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 18:21 UTC, merged